# docker-compose specs for rdw reporting service with the configuration server
# running in a container and MySQL running natively (outside the containers).
#
# The following environment variables MUST be set before running this spec, for config server:
# CONFIG_SERVICE_REPO - git repo url, e.g. https://gitlab.com/fairwaytech/rdw_config.git
# GIT_USER - user with rights to access CONFIG_SERVICE_REPO
# GIT_PASSWORD - password for GIT_USER
#
# This configuration maps the config folder as outlined in CONTRIBUTING.md and the application.yml file from the config
# server local-docker profile points to that folder so developers should be able to reuse the saml.jks file
# (NOTE: developers may have to explicitly share the /opt folder in Docker, Preferences, File Sharing)

version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  config-server:
    image: smarterbalanced/configuration-service:3.1.2-RELEASE
    container_name: config-server
    ports:
      - 8888:8888
    links:
      - rabbitmq
    environment:
      - CONFIG_SERVICE_REPO
      - ENCRYPT_KEY
      - CONFIG_SERVICE_SEARCH_PATH=tenant*
      - GIT_USER
      - GIT_PASSWORD
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 10s
      timeout: 2s
      retries: 6

  webapp:
    image: smarterbalanced/rdw-reporting-webapp
    ports:
      - 8080:8080
      - 8081:8008
    links:
      - config-server
      - admin-service
      - aggregate-service
      - report-processor-service
      - reporting-service
    depends_on:
      config-server:
        condition: service_healthy
# if running other services from IntelliJ, comment out the links entry (above) and
# change the zuul route to use the mac docker bridge; for example:
#        - zuul.routes.report-processor.url=http://host.docker.internal:8085
    environment:
      - spring.profiles.active=local-docker
      - datasources.reporting_ro.url-server=host.docker.internal:3306
      - zuul.routes.admin-service.url=http://admin-service:8080
      - zuul.routes.aggregate-service.url=http://aggregate-service:8080
      - zuul.routes.report-processor.url=http://report-processor-service:8080
      - zuul.routes.reporting-service.url=http://reporting-service:8080
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  admin-service:
    image: smarterbalanced/rdw-reporting-admin-service
    ports:
      - 8280:8080
      - 8208:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
      - aggregate-service
      - report-processor-service
      - reporting-service
    depends_on:
      config-server:
        condition: service_healthy
# if running other services from IntelliJ, comment out the links entry (above) and
# change the service route to use the mac docker bridge; for example:
#        - tenant-configuration-lookup.services.report-processor.url=http://host.docker.internal:8086
    environment:
      - spring.profiles.active=local-docker
      - tenant-configuration-lookup.services.admin-service.url=http://localhost:8008
      - tenant-configuration-lookup.services.aggregate-service.url=http://aggregate-service:8008
      - tenant-configuration-lookup.services.report-processor.url=http://report-processor-service:8008
      - tenant-configuration-lookup.services.reporting-service.url=http://reporting-service:8008
      - tenant-configuration-lookup.services.reporting-webapp.url=http://reporting-webapp:8008
      #     setup for tenant & sandbox administration local dev - needed to retrieve service configprops status
      #     all of these services were started up in intellij - and since adminService is running in docker
      #     needed to use the mac docker bridge and specific port used set in the VM config of each service
      #       rdw-ingest-import-service
#      - tenant-configuration-lookup.services.rdw-ingest-import-service.url=http://host.docker.internal:8089
#      #       rdw-ingest-exam-processor
#      - tenant-configuration-lookup.services.rdw-ingest-exam-processor.url=http://host.docker.internal:8090
#      #         rdw-ingest-group-processor
#      - tenant-configuration-lookup.services.rdw-ingest-group-processor.url=http://host.docker.internal:8087
#      #       rdw-ingest-package-processor
#      - tenant-configuration-lookup.services.rdw-ingest-package-processor.url=http://host.docker.internal:8083
#      #       rdw-ingest-task-service:
#      - tenant-configuration-lookup.services.rdw-ingest-task-service.url=http://host.docker.internal:8084
#      #       rdw-ingest-migrate-reporting
#      - tenant-configuration-lookup.services.rdw-ingest-migrate-reporting.url=http://host.docker.internal:8088
#      #       rdw-ingest-migrate-olap
#      - tenant-configuration-lookup.services.rdw-ingest-migrate-olap.url=http://host.docker.internal:8091
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  aggregate-service:
    image: smarterbalanced/rdw-reporting-aggregate-service
    ports:
      - 8380:8080
      - 8308:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
    depends_on:
      config-server:
        condition: service_healthy
    # to run this you'll probably need to set olap_ro credentials
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  reporting-service:
    image: smarterbalanced/rdw-reporting-service
    ports:
      - 8180:8080
      - 8108:8008
    links:
      - config-server
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  report-processor-service:
    image: smarterbalanced/rdw-reporting-report-processor
    ports:
      - 8085:8080
      - 8086:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
      - wkhtmltopdf
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  wkhtmltopdf:
    image: smarterbalanced/wkhtmltopdf-image:3.1.0
    ports:
      - 8082:80
