# docker-compose specs for rdw reporting service with the configuration server
# running in a container and MySQL running natively (outside the containers).
#
# The following environment variables MUST be set before running this spec, for config server:
# CONFIG_SERVICE_REPO - git repo url, e.g. https://gitlab.com/fairwaytech/rdw_config.git
# GIT_USER - user with rights to access CONFIG_SERVICE_REPO
# GIT_PASSWORD - password for GIT_USER
#
# This configuration maps the config folder as outlined in CONTRIBUTING.md and the application.yml file from the config
# server local-docker profile points to that folder so developers should be able to reuse the saml.jks file
# (NOTE: developers may have to explicitly share the /opt folder in Docker, Preferences, File Sharing)

version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  config-server:
    image: smarterbalanced/configuration-service:3.1.0.RELEASE
    container_name: config-server
    ports:
      - 8888:8888
    links:
      - rabbitmq
    environment:
      - CONFIG_SERVICE_REPO
      - ENCRYPT_KEY
      - GIT_USER
      - GIT_PASSWORD
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 10s
      timeout: 2s

  webapp:
    image: smarterbalanced/rdw-reporting-webapp
    ports:
      - 8080:8080
      - 8081:8008
    links:
      - config-server
      - admin-service
# uncomment to enable aggregate service
#      - aggregate-service
      - report-processor-service
      - reporting-service
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  admin-service:
    image: smarterbalanced/rdw-reporting-admin-service
    ports:
      - 8280:8080
      - 8208:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

# uncomment to enable aggregate service
#  aggregate-service:
#    image: smarterbalanced/rdw-reporting-aggregate-service
#    ports:
#      - 8380:8080
#      - 8308:8008
#    volumes:
#      - /tmp:/tmp
#    links:
#      - config-server
#    depends_on:
#      config-server:
#        condition: service_healthy
#    environment:
#      - spring.profiles.active=local-docker
#      - CONFIG_SERVICE_ENABLED=true
#      - CONFIG_SERVICE_URL=http://config-server:8888

  reporting-service:
    image: smarterbalanced/rdw-reporting-service
    ports:
      - 8180:8080
      - 8108:8008
    links:
      - config-server
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  report-processor-service:
    image: smarterbalanced/rdw-reporting-report-processor
    ports:
      - 8085:8080
      - 8086:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
      - wkhtmltopdf
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  wkhtmltopdf:
    image: smarterbalanced/wkhtmltopdf-image:3.1.0
    ports:
      - 8082:80
