spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reporting?useSSL=false
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: permissionsByRole

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      auto: false
      static: us-west-2

artifacts:
  root: "classpath:"
  exam-item:
    directory: data/irp/Item-{0}/
    file-name: item-{0}.xml

permissionservice:
  component: Reporting