spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reporting?useSSL=false
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false