sql:
  exam:
    findAllByStudentId: >-
      SELECT
        e.iep,
        e.lep,
        e.section504,
        e.economic_disadvantage,
        e.migrant_status,
        ${sql.snippet.claimColumns},
        ${sql.snippet.exam}
      WHERE e.student_id = :student_id
       AND ${sql.reporting.snippet.studentExamPermission}

    existsForStudentId: >-
      SELECT
        st.id,
        st.ssid,
        st.first_name,
        st.last_or_surname
      FROM student st
        JOIN exam e ON e.student_id = st.id
        JOIN asmt a ON a.id = e.asmt_id
        JOIN school s ON e.school_id = s.id
        JOIN school isch ON st.inferred_school_id = isch.id
      WHERE st.ssid = :student_ssid
      AND ${sql.reporting.snippet.studentExamPermission}
      LIMIT 1

  examItem:
      findAllForExam: >-
        ${sql.reporting.snippet.selectFromExamItem}
        WHERE e.id = :exam_id
        AND a.type_id != 3
        AND ${sql.reporting.snippet.studentExamPermission}

  group:
    assessment:
      findAll: >-
          SELECT distinct
           ${sql.reporting.snippet.assessmentColumns}
          FROM asmt a
            JOIN exam e ON e.asmt_id = a.id
            JOIN student_group_membership sgm ON e.student_id = sgm.student_id
            JOIN student_group sg ON sg.id = sgm.student_group_id
            JOIN school s ON e.school_id = s.id
            JOIN student st ON e.student_id = st.id
            JOIN school isch ON st.inferred_school_id = isch.id
          WHERE e.school_year = :school_year
            AND a.id = e.asmt_id
            AND sg.id = :group_id
            AND (sg.subject_id is null OR a.subject_id = sg.subject_id)
            AND ${sql.reporting.snippet.studentExamPermission}

      findLatestExam: >-
          SELECT
           ${sql.reporting.snippet.assessmentColumns}
          FROM exam e
            JOIN asmt a ON e.asmt_id=a.id
            JOIN student_group_membership sgm ON e.student_id=sgm.student_id
            JOIN student_group sg ON sg.id = sgm.student_group_id
            JOIN school s ON e.school_id=s.id
            JOIN student st ON e.student_id = st.id
            JOIN school isch ON st.inferred_school_id = isch.id
          WHERE e.school_year = :school_year
            AND sgm.student_group_id = :group_id
            AND (sg.subject_id is null OR a.subject_id = sg.subject_id)
            AND ${sql.reporting.snippet.studentExamPermission}
          ORDER BY e.completed_at desc
          LIMIT 1
    exam:
      findAllForAssessment: >-
        SELECT
          e.iep,
          e.lep,
          e.section504,
          e.economic_disadvantage,
          e.migrant_status,
          ${sql.snippet.claimColumns},
          ${sql.snippet.exam}
        JOIN student_group_membership sgm ON e.student_id=sgm.student_id
        JOIN student_group sg ON sg.id = sgm.student_group_id
        WHERE a.id = :assessment_id
          AND e.school_year = :school_year
          AND sg.id = :group_id
          AND (sg.subject_id is null OR a.subject_id = sg.subject_id)
          AND ${sql.reporting.snippet.studentExamPermission}

    examItem:
        findAllExamItemScoresForAssessment:
          ${sql.reporting.snippet.selectFromExamItem}
            JOIN student_group_membership sgm ON e.student_id=sgm.student_id
            JOIN student_group sg ON sg.id = sgm.student_group_id
          WHERE e.asmt_id = :assessment_id
            AND e.school_year = :school_year
            AND sg.id = :group_id
            AND (sg.subject_id is null OR a.subject_id = sg.subject_id)
            AND ${sql.reporting.snippet.studentExamPermission}

  schoolgrade:
    assessment:
      findAll: >-
        SELECT ${sql.reporting.snippet.assessmentColumns}
        FROM asmt a
        WHERE EXISTS (
            SELECT e.asmt_id
            FROM exam e
              JOIN school s ON e.school_id = s.id
              JOIN student st ON e.student_id = st.id
              JOIN school isch ON st.inferred_school_id = isch.id
            WHERE e.school_year = :school_year
            AND a.id = e.asmt_id
            AND (s.id = :school_id OR (1 = :allow_transfer_access AND isch.id = :school_id))
            AND ${sql.reporting.snippet.studentExamPermission}
        )
        AND a.grade_id = :grade_id

      findLatestExam: >-
        SELECT 
          ${sql.reporting.snippet.assessmentColumns}
        FROM exam e
          JOIN asmt a ON e.asmt_id=a.id
          JOIN school s ON e.school_id=s.id
          JOIN student st ON e.student_id = st.id
          JOIN school isch ON st.inferred_school_id = isch.id
        WHERE e.school_year = :school_year
        AND e.school_id = :school_id
        AND a.grade_id = :grade_id
        AND ${sql.reporting.snippet.studentExamPermission}
        ORDER BY e.completed_at desc
        LIMIT 1

    exam:
      findAllForAssessment: >-
        SELECT
          e.iep,
          e.lep,
          e.section504,
          e.economic_disadvantage,
          e.migrant_status,
          ${sql.snippet.claimColumns},
          ${sql.snippet.exam}
        WHERE a.id = :assessment_id
        AND a.grade_id = :grade_id
        AND e.school_year = :school_year
        AND (s.id = :school_id OR (1 = :allow_transfer_access AND isch.id = :school_id))
        AND ${sql.reporting.snippet.studentExamPermission}

    examItem:
        findAllExamItemScoresForAssessment:
          ${sql.reporting.snippet.selectFromExamItem}
          WHERE e.asmt_id = :assessment_id
          AND e.school_year = :school_year
          AND a.grade_id = :grade_id
          AND (s.id = :school_id OR (1 = :allow_transfer_access AND isch.id = :school_id))
          AND ${sql.reporting.snippet.studentExamPermission}

  assessment:
    grade:
      findAllForSchool: >-
        SELECT id, code
        FROM grade g WHERE EXISTS (
            SELECT a.grade_id
            FROM exam e
              JOIN asmt a ON a.id = e.asmt_id
              JOIN school s ON e.school_id = s.id
              JOIN student st ON e.student_id = st.id
              JOIN school isch ON st.inferred_school_id = isch.id
            WHERE e.school_id = :school_id
            AND ${sql.reporting.snippet.studentExamPermission}
            AND g.id=a.grade_id
        )

  reporting:
    snippet:
      assessmentColumns: >-
          a.id,
          a.label,
          a.grade_code,
          a.type_id,
          a.subject_id,
          a.school_year,
          a.claim1_score_code,
          a.claim2_score_code,
          a.claim3_score_code,
          a.claim4_score_code,
          a.min_score,
          a.max_score,
          a.cut_point_1,
          a.cut_point_2,
          a.cut_point_3

      selectFromExamItem: >-
           SELECT
              ei.id,
              ei.exam_id,
              ei.item_id,
              ei.score,
              ei.position,
              ei.response,
              ei.trait_evidence_elaboration_score,
              ei.trait_organization_purpose_score,
              ei.trait_conventions_score
            FROM exam_item ei
            JOIN exam e ON ei.exam_id=e.id
            JOIN asmt a ON e.asmt_id=a.id
            JOIN school s ON e.school_id=s.id
            JOIN student st ON st.id=e.student_id
            JOIN school isch ON st.inferred_school_id = isch.id
            
      studentExamPermission: >-
          ${sql.snippet.studentExamPermissionNoEmbargo}
          AND
          (
             e.school_year < ${app.school-year}
             OR e.type_id <> 3
             OR s.embargo_enabled = 0
             OR 1 = :state_embargo_admin
             OR s.district_id IN (:district_embargo_admin_ids)
          )
