sql:
  administrationCondition:
    findAll: >-
      SELECT id, code FROM administration_condition ORDER BY id

  altScore:
    findAll: >-
      SELECT ss.id, ss.code, s.code as subject_code, at.code as asmt_type_code
        FROM subject_score ss
          JOIN subject s ON ss.subject_id = s.id
          JOIN asmt_type at ON at.id = ss.asmt_type_id
        WHERE ss.score_type_id = 2

  assessment:
    findAll: >-
      SELECT a.id,
        a.name,
        a.label,
        at.code as type_code,
        s.code as subject_code,
        g.code as grade_code,
        g.sequence as grade_sequence,
        a.school_year,
        a.min_score,
        a.cut_point_1,
        a.cut_point_2,
        a.cut_point_3,
        a.cut_point_4,
        a.cut_point_5,
        a.max_score
      FROM asmt a
        JOIN asmt_type at on at.id = a.type_id
        JOIN subject s on s.id = a.subject_id
        JOIN grade g on g.id =  a.grade_id

  assessmentGrade:
    findAll: >-
      SELECT DISTINCT
        g.id,
        g.code,
        g.sequence
      FROM asmt a
        JOIN grade g ON g.id = a.grade_id
      ORDER BY id

  assessmentType:
    findAll: >-
      SELECT id, code FROM asmt_type ORDER BY id

  claim:
    findAll: >-
      SELECT ss.id, ss.code, s.code as subject_code, at.code as asmt_type_code
        FROM subject_score ss
          JOIN subject s ON ss.subject_id = s.id
          JOIN asmt_type at ON at.id = ss.asmt_type_id
        WHERE ss.score_type_id = 3

  target:
    findAll: >-
      SELECT t.id, t.natural_id, t.claim_code, at.asmt_id, at.include_in_report
        FROM asmt_target at
          JOIN target t ON at.target_id =  t.id

  completeness:
    findAll: >-
      SELECT id, code FROM completeness ORDER BY id

  elas:
    findAll: >-
      SELECT id, code FROM elas ORDER BY id

  language:
    findAll: >-
      SELECT id, code FROM language ORDER BY id

  militaryConnectedCode:
    findAll: >-
      SELECT id, code FROM military_connected ORDER BY id

  gender:
    findAll: >-
      SELECT id, code FROM gender ORDER BY id

  boolean:
    findAll: SELECT id, code FROM boolean ORDER BY id

  strictBoolean:
    findAll: SELECT id, code FROM strict_boolean ORDER BY id

  embargo:
    isStateEmbargoed: >-
      SELECT EXISTS(SELECT 1 FROM state_embargo WHERE aggregate = 1) as embargo_enabled

    findAllEmbargoedDistrictIds: >-
      SELECT id FROM district d WHERE EXiSTS (SELECT 1 FROM school WHERE embargo_enabled = 1 AND district_id = d.id)

    loadingVisible: >-
      SELECT EXISTS(
        SELECT 1
            FROM school_year y
              JOIN district d ON 1=1
              JOIN subject s ON 1=1
              LEFT JOIN district_embargo de ON
                      y.year = de.school_year and
                      d.id = de.district_id and
                      s.id = de.subject_id
            WHERE
              CASE coalesce(de.aggregate, 0)
                WHEN 0 THEN :state_embargo_loading = 1 OR d.id IN (:district_ids_embargo_loading)
              END
        LIMIT 1) AS embargo_enabled

    reviewingVisible: >-
      SELECT EXISTS(
        SELECT 1
            FROM school_year y
              JOIN district d ON 1=1
              JOIN subject s ON 1=1
              LEFT JOIN district_embargo de ON
                      y.year = de.school_year and
                      d.id = de.district_id and
                      s.id = de.subject_id
            WHERE
              CASE coalesce(de.aggregate, 0)
                WHEN 1 THEN :state_embargo_loading = 1 OR :state_embargo_reviewing = 1 OR d.id IN (:district_ids_embargo_loading) OR d.id IN (:district_ids_embargo_reviewing)
              END
        LIMIT 1) AS embargo_enabled

  organization:
    aggregate:
      findAllSchools: >-
        SELECT
          id AS organization_id,
          name AS organization_name,
          natural_id AS organization_natural_id,
          'School' as organization_type,
          district_id
        FROM school

      findAllDistricts: >-
        SELECT
          id AS organization_id,
          name AS organization_name,
          natural_id AS organization_natural_id,
          'District' as organization_type
        FROM district

  schoolYear:
    findAll: >-
      SELECT year
      FROM school_year
      ORDER BY year DESC

  studentEthnicity:
    findAll: >-
      SELECT id,
        code
      FROM ethnicity
      ORDER BY id

  subject:
    findAll: >-
      SELECT
        s.id,
        s.code,
        sat.target_report,
        at.code as asmt_type_code
      FROM subject s
        JOIN subject_asmt_type sat ON s.id = sat.subject_id
        JOIN asmt_type at ON at.id = sat.asmt_type_id
      ORDER BY s.id

  activeAsmt:
    findAllByType: >-
       SELECT
         a.id as asmt_id,
         g.code as asmt_grade_code,
         ay.school_year,
         s.code as subject_code,
         a.label as asmt_label
       FROM asmt_active_year ay
         JOIN asmt a ON a.id = ay.asmt_id
         JOIN subject s ON s.id = a.subject_id
         JOIN asmt_type at on at.id = a.type_id
         JOIN grade g on g.id = a.grade_id
        WHERE at.code= :asmt_type_code
