# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  port: 8008
  security:
    enabled: false
  # disable health check for tenant-specific features
  health:
    db:
      enabled: false

# configure actuator endpoints to unmask "key" properties so tenant keys won't be masked. However, we still
# mask secret keys (i.e. props ending with secretKey, secret-key, or secret_key in lower, upper, or mixed case)
endpoints:
  env:
    keys-to-sanitize: password,secret,token,.*credentials.*,vcap_services,secret[-_]?key
  configprops:
    keys-to-sanitize: password,secret,token,.*credentials.*,vcap_services,secret[-_]?key

app:
  aggregate-reports:
    custom-aggregate-report-repository:
      organization-partition-size: 10
      jdbc-fetch-size: -1
    query-pool-size: 6
    api-enabled: false

  cache:
    repository:
      # every day at 2:00 am (GMT)
      refresh-cron: "0 0 2 * * *"

#Per tenant configuration options
aggregate-reporting:
  assessment-types: ica,sum,iab
  statewide-user-assessment-types: sum
  state-aggregate-assessment-types: sum

archive:
  uri-root: "file:///tmp/"
  #path-prefix:
  #s3-access-key:
  #s3-secret-key:
  s3-region-static: us-west-2
  #s3-sse:

jwt:
  secret: ${rdw.reporting.jwt.secret:secret}

reporting:
  school-year: 2019
  target-report:
    insufficient-data-cutoff: 0.2
    min-number-of-students: 0
  student-fields:
    EconomicDisadvantage: Enabled
    EnglishLanguageAcquisitionStatus: Disabled
    Ethnicity: Enabled
    Gender: Enabled
    IndividualEducationPlan: Enabled
    LimitedEnglishProficiency: Enabled
    MigrantStatus: Enabled
    MilitaryStudentIdentifier: Enabled
    PrimaryLanguage: Enabled
    Section504: Enabled

server:
  # tomcat settings for reasonable performance: adjust for tiny/huge configurations
  tomcat:
    max-connections: 0
    max-threads: 4
    accept-count: 10

spring:
  cache:
    type: SIMPLE
    cache-names: reportOptions, administrationConditions, assessments, assessmentGrades, assessmentTypes, booleans, strictBooleans, organizations, completenessCodes, claims, targets, ethnicities, genders, elases, languages, militaryConnectedCodes, schoolYears, subjects, activeAssessments, embargo

  cloud:
    stream:
      bindings:
        AggregateRequest:
          content-type: application/json
          group: default
          producer:
            requiredGroups: default

        AggregateResponse:
          content-type: application/json
          group: default
          producer:
            requiredGroups: default

        ConfigpropsUpdateOutput:
          destination: ConfigpropsUpdateExchange

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

datasources:
  olap_ro:
    url-parts:
      protocol: "jdbc:redshift:"
      hosts: "${datasources.olap_ro.url-server:localhost:5432}"
      database: "${datasources.olap_ro.url-db:dev}"
      properties: "ApplicationName=rdw-reporting-aggregate-service\
                   &loginTimeout=${datasources.olap_ro.connect-timeout:10}\
                   &socketTimeout=${datasources.olap_ro.socket-timeout:0}\
                   "
    url: "${datasources.olap_ro.url-parts.protocol}//${datasources.olap_ro.url-parts.hosts}/${datasources.olap_ro.url-parts.database}?${datasources.olap_ro.url-parts.properties}"
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationInterval: 35000
    driverClassName: com.amazon.redshift.jdbc42.Driver
