sql:

  administrationCondition:
    findAll: >-
      SELECT id,
        code
      FROM administration_condition
      ORDER BY id

  assessmentGrade:
    findAll: >-
      SELECT DISTINCT
        g.id,
        g.code
      FROM asmt a
        JOIN grade g ON g.id = a.grade_id
      ORDER BY id

  assessmentType:
    findAll: >-
      SELECT id,
        code
      FROM asmt_type
      ORDER BY id

  completeness:
    findAll: >-
      SELECT id,
        code
      FROM completeness
      ORDER BY id

  gender:
    findAll: >-
      SELECT id,
        code
      FROM gender
      ORDER BY id

  boolean:
    findAll: select id, code from boolean order by id

  strictBoolean:
    findAll: select id, code from strict_boolean order by id

  organization:
    aggregate:
      findAllSchools: >-
        SELECT
          id AS organization_id,
          name AS organization_name,
          natural_id AS organization_natural_id,
          'School' as organization_type,
          district_id,
          embargo_enabled
        FROM school

      findAllDistricts: >-
        SELECT DISTINCT
          s.district_id AS organization_id,
          d.name AS organization_name,
          d.natural_id AS organization_natural_id,
          'District' as organization_type,
          s.embargo_enabled
        FROM school s
          JOIN district d on s.district_id = d.id

      isStateEmbargoEnabled: >-
        SELECT EXISTS(SELECT 1FROM state_embargo WHERE aggregate = 1) as embargo_enabled

  schoolYear:
    findAll: >-
      SELECT year
      FROM school_year
      ORDER BY year DESC

  studentEthnicity:
    findAll: >-
      SELECT id,
        code
      FROM ethnicity
      ORDER BY id

  subject:
    findAll: >-
      SELECT id,
        code
      FROM subject
      ORDER BY id

  activeAsmt:
    findAllByType: >-
       SELECT
         a.id as asmt_id,
         g.code as asmt_grade_code,
         ay.school_year,
         s.code as subject_code,
         a.label as asmt_label
       FROM asmt_active_year ay
         JOIN asmt a ON a.id = ay.asmt_id
         JOIN subject s ON s.id = a.subject_id
         JOIN asmt_type at on at.id = a.type_id
         JOIN grade g on g.id = a.grade_id
        WHERE at.code= :asmt_type_code