# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  security:
    enabled: false

server:
  # tomcat settings for reasonable performance: adjust for tiny/huge configurations
  tomcat:
    max-connections: 0
    max-threads: 4
    accept-count: 10
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,text/csv

spring:
  reporting_ro_datasource:
    url-parts:
      #This is the generic format of the connection URL protocol//[hosts][/database][?properties]
      protocol: "jdbc:mysql:"
      hosts: "${spring.reporting_ro_datasource.url-server:localhost:3306}"
      database: "${spring.reporting_ro_datasource.url-schema:reporting}"
      properties: "useSSL=${spring.reporting_ro_datasource.use-ssl:false}\
                   &useLegacyDatetimeCode=${spring.reporting_ro_datasource.use-legacy-datetime-code:false}\
                   &characterEncoding=${spring.reporting_ro_datasource.character-encoding:utf8}\
                   &rewriteBatchedStatements=${spring.reporting_ro_datasource.rewrite-batched-statements:true}\
                   &connectTimeout=${spring.reporting_ro_datasource.connect-timeout:10000}\
                   &socketTimeout=${spring.reporting_ro_datasource.socket-timeout:40000}\
                   "
    url: "${spring.reporting_ro_datasource.url-parts.protocol}//${spring.reporting_ro_datasource.url-parts.hosts}/${spring.reporting_ro_datasource.url-parts.database}?${spring.reporting_ro_datasource.url-parts.properties}"
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${spring.reporting_ro_datasource.query-timeout:30})"
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    initialSize: 4
    maxActive: 10
    minIdle: ${spring.reporting_ro_datasource.initialSize}
    maxIdle: ${spring.reporting_ro_datasource.maxActive}
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false

  warehouse_datasource:
    url-parts:
      #This is the generic format of the connection URL protocol//[hosts][/database][?properties]
      protocol: "jdbc:mysql:"
      hosts: "${spring.warehouse_datasource.url-server:localhost:3306}"
      database: "${spring.warehouse_datasource.url-schema:warehouse}"
      properties: "useSSL=${spring.warehouse_datasource.use-ssl:false}\
                   &useLegacyDatetimeCode=${spring.warehouse_datasource.use-legacy-datetime-code:false}\
                   &characterEncoding=${spring.warehouse_datasource.character-encoding:utf8}\
                   &connectTimeout=${spring.warehouse_datasource.connect-timeout:10000}\
                   &socketTimeout=${spring.warehouse_datasource.socket-timeout:70000}\
                   "
    url: "${spring.warehouse_datasource.url-parts.protocol}//${spring.warehouse_datasource.url-parts.hosts}/${spring.warehouse_datasource.url-parts.database}?${spring.warehouse_datasource.url-parts.properties}"
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${spring.warehouse_datasource.query-timeout:60})"
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    initialSize: 4
    maxActive: 10
    minIdle: ${spring.warehouse_datasource.initialSize}
    maxIdle: ${spring.warehouse_datasource.maxActive}
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false

  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  # Force the (rabbit) queues to be created when posting messages so, even if
  # there are no consumers running, the messages will not get lost. Routing is
  # dynamic based on content but there is no way to do that here so we must
  # explicitly declare all possible output channels here (EXAM, PACKAGE, etc.).
  # The group names must be coordinated with the consumer application configs.
  cloud:
    stream:
      bindings:
        output:
          destination: GROUPS
          group: default

# spring auto-configured aws defense
cloud:
  aws:
    # there must be a default region when running locally
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

# Needed for access to S3

# Location of import archive.
archive:
  root: file:///tmp/

jwt:
  secret: ${rdw.reporting.jwt.secret:secret}

reporting:
  school-year: 2019
  state:
    code: CA
    name: California
