# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  port: 8008
  security:
    enabled: false
  # disable health check for tenant-specific features
  health:
    db:
      enabled: false

spring:
  batch:
    job:
      enabled: false
  cache:
    type: SIMPLE
    cache-names: translations, subjects, subjectdefinitions
  cloud:
    stream:
      bindings:
        ReportExportExamsOut:
          content-type: application/json
          destination: ReportExportExams
          group: default
          producer:
            requiredGroups: default

        ReportExportExamsIn:
          content-type: application/json
          destination: ReportExportExams
          group: default

        ReportFetchStudentsOut:
          content-type: application/json
          destination: ReportFetchStudents
          group: default
          producer:
            requiredGroups: default

        ReportFetchStudentsIn:
          content-type: application/json
          destination: ReportFetchStudents
          group: default

        ReportGenerateForStudentsOut:
          content-type: application/json
          destination: ReportGenerateForStudents
          group: default
          producer:
            requiredGroups: default

        ReportGenerateForStudentsIn:
          content-type: application/json
          destination: ReportGenerateForStudents
          group: default
          consumer:
            concurrency: 2

        ReportCollateOut:
          content-type: application/json
          destination: ReportCollate
          group: default
          producer:
            requiredGroups: default

        ReportCollateIn:
          content-type: application/json
          destination: ReportCollate
          group: default

        ReportAggregateReportsOut:
          content-type: application/json
          destination: ReportAggregateReports
          group: default
          producer:
            requiredGroups: default

        ReportAggregateReportsIn:
          content-type: application/json
          destination: ReportAggregateReports
          group: default

        AggregateRequest:
          content-type: application/json
          group: default
          producer:
            requiredGroups: default

        AggregateResponse:
          content-type: application/json
          group: default
          producer:
            requiredGroups: default

  jackson:
      default-property-inclusion: non_null
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  thymeleaf:
    mode: HTML

datasources:
  reporting_ro:
    url-parts:
      #This is the generic format of the connection URL protocol//[hosts][/database][?properties]
      protocol: "jdbc:mysql:"
      hosts: "${datasources.reporting_ro.url-server:localhost:3306}"
      database: "${datasources.reporting_ro.url-schema:reporting}"
      properties: "useSSL=${datasources.reporting_ro.use-ssl:false}\
                   &useLegacyDatetimeCode=${datasources.reporting_ro.use-legacy-datetime-code:false}\
                   &characterEncoding=${datasources.reporting_ro.character-encoding:utf8}\
                   &rewriteBatchedStatements=${datasources.reporting_ro.rewrite-batched-statements:true}\
                   &connectTimeout=${datasources.reporting_ro.connect-timeout:10000}\
                   &socketTimeout=${datasources.reporting_ro.socket-timeout:600000}\
                   "
    url: "${datasources.reporting_ro.url-parts.protocol}//${datasources.reporting_ro.url-parts.hosts}/${datasources.reporting_ro.url-parts.database}?${datasources.reporting_ro.url-parts.properties}"
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${datasources.reporting_ro.query-timeout:120})"
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    initialSize: 4
    maxActive: 20
    minIdle: ${datasources.reporting_ro.initialSize}
    maxIdle: ${datasources.reporting_ro.maxActive}
    maxWait: 10000
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false

archive:
  uri-root: "file:///tmp/"
  #path-prefix:
  #s3-access-key:
  #s3-secret-key:
  s3-region-static: us-west-2
  #s3-sse:

app:
  wkhtmltopdf:
    url: http://localhost:8082
    options:
      page-size: Letter
      zoom: 0.75

jwt:
  secret: ${rdw.reporting.jwt.secret:secret}

reporting:
  school-year: 2019
  state:
    code: CA
    name: California
