sql:
  report:
    create: >-
      insert into user_report
        (user_login, status, report_resource_uri, label, report_request, report_type, created)
        values
        (:user_login, :status, :report_resource_uri, :label, :report_request, :report_type, :created)

    update: >-
      update user_report
      set
        user_login = :user_login,
        status = :status,
        report_resource_uri = :report_resource_uri,
        label = :label,
        report_request = :report_request,
        created = :created
      where
        id = :id

    findAllByUser: >-
      ${sql.reportProcessor.snippet.selectFromUserReport}
      where r.user_login = :user
      order by r.id desc

    findAllByUserAndId: >-
      ${sql.reportProcessor.snippet.selectFromUserReport}
      where r.user_login = :user
        and r.id in (:report_ids)
      order by r.id desc

    findById: >-
      ${sql.reportProcessor.snippet.selectFromUserReport}
      where r.id = :report_id

    findAllOlderThanNumberOfDays: >-
      ${sql.reportProcessor.snippet.selectFromUserReport}
      where r.created < date_sub(now(), interval :number_of_days day);

    deleteByIds: >-
      delete from `user_report` WHERE `id` in (:ids);

    completeChunk: >-
      update user_report_metadata
        set value = cast(LAST_INSERT_ID(cast(value as unsigned) + 1) AS CHAR)
      where
        report_id = :report_id and
        name = 'completed_chunk_count';

    insertMetadataForReport: >-
      insert into user_report_metadata
        (report_id, name, value)
        values
        (:report_id, :name, :value);

    deleteMetadataForReport: >-
      delete from user_report_metadata
      where
        report_id = :report_id;

    findMetadataForReports: >-
      select * from user_report_metadata
      where
        report_id IN (:report_ids);

  reportProcessor:
    snippet:
      selectFromUserReport: >-
          select
              r.id,
              r.user_login,
              r.status,
              r.report_resource_uri,
              r.label,
              r.report_request,
              r.created
            from user_report r