# docker-compose specs for RDW report processor in a container and MySQL running natively (outside the containers).
#
# The following environment variables MUST be set before running this spec:
#
# DATAWAREHOUSE_HOST - host running mysql with rdw reporting schema initialized
# For mac developers running mysql natively, something like:
#   $ export DATAWAREHOUSE_HOST=$(ipconfig getifaddr en0)
# This value may have to be reset when you change networks.
#
# CONFIG_SERVICE_REPO - git repo url, e.g. https://gitlab.com/fairwaytech/sbac-config-repo.git
# GIT_USER - user with rights to access CONFIG_SERVICE_REPO
# GIT_PASSWORD - password for GIT_USER

version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  config-server:
    image: smarterbalanced/configuration-service:3.1.0.RELEASE
    container_name: config-server
    ports:
      - 8888:8888
    links:
      - rabbitmq
    environment:
      - CONFIG_SERVICE_REPO
      - ENCRYPT_KEY
      - GIT_USER
      - GIT_PASSWORD
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  report-processor-service:
    image: smarterbalanced/rdw-reporting-report-processor
    ports:
      - 8085:8080
      - 8086:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
      - wkhtmltopdf
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
      - task.remove-stale-reports.cron=0 1 * * * *
      - task.remove-stale-reports.max-report-lifetime-days=30
      - task.remove-stale-reports.max-random-minutes=0
    extra_hosts:
      - "dwhost:$DATAWAREHOUSE_HOST"

  wkhtmltopdf:
    image: smarterbalanced/wkhtmltopdf-image:latest
    ports:
      - 8082:80