sql:
  report:

    insert: >-
      insert into user_report
        (user_login, job_execution_id, status, report_resource_uri, label, report_request, created)
        values
        (:user_login, :job_execution_id, :status, :report_resource_uri, :label, :report_request, :created)

    update: >-
      update user_report
      set
        user_login = :user_login,
        job_execution_id = :job_execution_id,
        status = :status,
        report_resource_uri = :report_resource_uri,
        label = :label,
        report_request = :report_request,
        created = :created
      where
        id = :id

    findAllByUser: >-
      select
        r.id,
        r.user_login,
        r.job_execution_id,
        r.status,
        r.report_resource_uri,
        r.label,
        r.report_request,
        r.created
      from user_report r
      where r.user_login = :user
      order by r.id desc

    findAllByUserAndId: >-
      select
        r.id,
        r.user_login,
        r.job_execution_id,
        r.status,
        r.report_resource_uri,
        r.label,
        r.report_request,
        r.created
      from user_report r
      where r.user_login = :user
        and r.id in (:report_ids)
      order by r.id desc

    findById: >-
      select
        r.id,
        r.user_login,
        r.job_execution_id,
        r.status,
        r.report_resource_uri,
        r.label,
        r.report_request,
        r.created
      from user_report r
      where r.id = :report_id

  studentId:
    findByExamFilter:
      select
        distinct st.id
      from student st
        join exam e on e.student_id = st.id
        join asmt a on e.asmt_id=a.id
        join school s on e.school_id = s.id
      where ((-1)=:school_year or e.school_year=:school_year)
        and ((-1)=:school_id or s.id=:school_id)
        and ((-1)=:subject_id or a.subject_id=:subject_id)
        and ((-1)=:grade_id or e.grade_id=:grade_id)
        and ((-1)=:assessment_type or a.type_id=:assessment_type)
        and (1=:statewide or s.district_id in (:district_ids) or e.school_id in (:school_ids))