# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: exam_report_pdf
          group: default

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: internalTranslationsByCode

cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false