# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false

server:
  port: 8008

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: internalTranslationsByCode

  cloud:
    stream:
      bindings:
        input:
          destination: exam_report_pdf
          group: default

  thymeleaf:
    mode: HTML

cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

app:
  state:
    code: CA

  datamart:
    datasource:
      url: jdbc:mysql://localhost:3306/reporting?useSSL=false&useLegacyDatetimeCode=false
      username: root
      password:
      testWhileIdle: true
      validationQuery: SELECT 1
      driverClassName: com.mysql.jdbc.Driver
      initialize: false

  batch:
    datasource:
      url: jdbc:mysql://localhost:3306/spring_batch_reporting?useSSL=false&useLegacyDatetimeCode=false
      username: root
      password:
      testWhileIdle: true
      validationQuery: SELECT 1
      driverClassName: com.mysql.jdbc.Driver
      initialize: false

  wkhtmltopdf:
    url: http://wkhtmltopdf/
    options:
      dpi: 276
      page-size: Letter
