# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  health:
    redis:
      enabled: false

saml:
  # SAML keystore path: file:/some/path/saml.jks
  key-store-file: ${rdw.reporting.keystore.path}
  key-store-password: ${rdw.reporting.keystore.password}
  private-key-entry-alias: ${rdw.reporting.keystore.alias}
  private-key-entry-password: ${rdw.reporting.keystore.entry.password}
  idp-metadata-url: ${rdw.reporting.idp}
  sp-entity-id: ${rdw.reporting.entityId}
  # SAML settings when hosting behind a load balancer or reverse proxy
  load-balance:
    enabled: false
    scheme: https
    hostname:
    context-path: /
    port: 8080
    include-server-port: false

server:
  # tomcat settings for reasonable performance: adjust for tiny/huge configurations
  tomcat:
    max-connections: 0
    max-threads: 4
    accept-count: 10
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,text/csv

spring:
  resources:
    chain:
      enabled: true
      gzipped: true

  session:
    store-type: none

  # still need this for translations api
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: permissionsByRole, internalTranslationsByCode, mergeTranslations

security:
  filter-dispatcher-types: FORWARD, INCLUDE, REQUEST, ASYNC, ERROR

permissionservice:
  component: Reporting
  endpoint: ${rdw.permission.service}

app:
  # todo use tenant.code & name
  state:
    code: CA
    name: California

  datamart:
    datasource:
      url: "\
        jdbc:mysql://${app.datamart.datasource.url-server:localhost:3306}/${app.datamart.datasource.url-schema:reporting}\
        ?useSSL=${app.datamart.datasource.use-ssl:false}\
        &useLegacyDatetimeCode=${app.datamart.datasource.use-legacy-datetime-code:false}\
        &characterEncoding=${app.datamart.datasource.character-encoding:utf8}\
        &useCompression=${app.datamart.datasource.use-compression:true}\
        "
      username: root
      password:
      testWhileIdle: true
      validationQuery: SELECT 1
      driverClassName: com.mysql.jdbc.Driver
      initialize: false

  iris:
    url: ${rdw.reporting.iris.url}

# Netflix zuul configuration.
zuul:
  set-content-length: true
  FormBodyWrapperFilter:
    pre: disable
  host:
    socket-timeout-millis: 100000
  routes:
    iris:
      path: /iris/**
      url: ${app.iris.url}
      stripPrefix: true
    admin-service:
      path: /api/admin-service/**
      url: http://localhost:8280
      stripPrefix: true
    report-processor:
      path: /api/report-processor/**
      url: http://localhost:8085
      stripPrefix: true
    reporting-service:
      path: /api/reporting-service/**
      url: http://localhost:8180
      stripPrefix: true

jwt:
  secret: ${rdw.reporting.jwt.secret:secret}
  producer: true
  routePaths: ${zuul.routes.admin-service.path},${zuul.routes.report-processor.path},${zuul.routes.reporting-service.path}
