sql:
  group:
    findAllForUsername: >-
      select sg.id, sg.name, school.name as school_name, subject_id
        from user_student_group usg
          join student_group sg on sg.id = usg.student_group_id
          join school on school.id = sg.school_id
        where user_login=:user_login

    membership:
      findAllForUsername: >-
        select sg.id, sg.subject_id, sg.school_id
          from user_student_group usg
            join student_group sg on sg.id = usg.student_group_id
          where user_login=:user_login

    assessment:
      findLatest: >-
        select
            e.completed_at,
            a.id as assessment_id,
            a.name as assessment_name,
            a.grade_id as assessment_grade_id,
            a.type_id as assessment_type_id,
            a.subject_id as assessment_subject_id
          from exam e
            join student_group_membership sgm on e.student_id=sgm.student_id
            join asmt a on e.asmt_id=a.id
            join school s on e.school_id=s.id
          where year(cast(e.completed_at as date))=:year
          and sgm.student_group_id=:group_id
          and (0=:group_subject_id or a.subject_id=:group_subject_id)
          and (1=:statewide or s.district_id in (:district_ids) or e.school_id in (:school_ids))
          order by e.completed_at desc
          limit 1

      iab:
        findLatest: >-
          select
              e.completed_at,
          	  a.id as assessment_id,
              a.name as assessment_name,
              a.grade_id as assessment_grade_id,
              a.type_id as assessment_type_id,
              a.subject_id as assessment_subject_id
            from iab_exam e
              join student_group_membership sgm on e.student_id=sgm.student_id
              join asmt a on e.asmt_id=a.id
              join school s on e.school_id=s.id
            where year(cast(e.completed_at as date))=:year
            and sgm.student_group_id=:group_id
            and (0=:group_subject_id or a.subject_id=:group_subject_id)
            and (1=:statewide or s.district_id in (:district_ids) or e.school_id in (:school_ids))
            order by e.completed_at desc
            limit 1

  district:
    findAllIds: >-
      select natural_id, id
        from district
        where natural_id in (:naturalIds)

  school:
    findAllIds: >-
      select natural_id, id
        from school
        where natural_id in (:naturalIds)
