# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  security:
    enabled: false

saml:
  # SAML keystore path: file:/some/path/saml.jks
  key-store-file: ${rdw.reporting.keystore.path}
  key-store-password: ${rdw.reporting.keystore.password}
  private-key-entry-alias: ${rdw.reporting.keystore.alias}
  private-key-entry-password: ${rdw.reporting.keystore.entry.password}
  idp-metadata-url: ${rdw.reporting.idp}
  sp-entity-id: ${rdw.reporting.entityId}

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: permissionsByRole, internalTranslationsByCode

  cloud:
    stream:
      bindings:
        output:
          destination: exam_report_pdf
          group: default

  thymeleaf:
    mode: HTML

cloud:
  aws:
    credentials:
      #AWS credentials are necessary if reading assessment files from S3
      accessKey: ${rdw.aws.access.key:}
      secretKey: ${rdw.aws.secret.key:}
      instance-profile: false
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false

artifacts:
  #Root location of assessment files [s3://some-bucket/ | classpath: | etc]
  root: ${rdw.resource.root:"classpath:"}
  exam-item:
    directory: ${rdw.reporting.artifacts.exam.item.directory:local/items/Item-{0}/}
    file-name: item-{0}.xml

permissionservice:
  component: Reporting
  endpoint: ${rdw.permission.service}

app:
  state:
    code: CA

  datamart:
    datasource:
      url: jdbc:mysql://localhost:3306/reporting?useSSL=false&useLegacyDatetimeCode=false
      username: root
      password:
      testWhileIdle: true
      validationQuery: SELECT 1
      driverClassName: com.mysql.jdbc.Driver
      initialize: false

  iris:
    vendorId: ${rdw.reporting.iris.vendorId}
    url: ${rdw.reporting.iris.url}

  # google analytics configuration
  analytics:
    trackingId: ${rdw.reporting.analytics.trackingId:}

  wkhtmltopdf:
    url: http://localhost:8082
    options:
      dpi: 276
      page-size: Letter
      user-style-sheet: http://localhost:8080/assets/css/sbac-ui-kit-wkhtmltopdf.min.css

  external-links:
    interpretive-guide: http://www.smarterbalanced.org/educators/
