# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  security:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reporting?useSSL=false
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: permissionsByRole, internalTranslationsByCode

  cloud:
    stream:
      bindings:
        output:
          destination: exam_report_pdf
          group: default

cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

artifacts:
  root: "classpath:"
  exam-item:
    directory: data/irp/Item-{0}/
    file-name: item-{0}.xml

permissionservice:
  component: Reporting