# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  security:
    enabled: false

saml:
  # SAML keystore path: file:/some/path/saml.jks
  key-store-file: ${reporting.keystore}
  key-store-password: ${reporting.keystore.password}
  private-key-entry-alias: ${reporting.keystore.alias}
  private-key-entry-password: ${reporting.keystore.entry.password}
  idp-metadata-url: ${reporting.idp}
  sp-entity-id: ${reporting.entityId}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reporting?useSSL=false&useLegacyDatetimeCode=false
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cache:
    type: SIMPLE
    cache-names: permissionsByRole, internalTranslationsByCode

  cloud:
    stream:
      bindings:
        output:
          destination: exam_report_pdf
          group: default

cloud:
  aws:
    credentials:
      #AWS credentials are necessary if reading assessment files from S3
      accessKey: ${rdw.aws.access.key}
      secretKey: ${rdw.aws.secret.key}
      instance-profile: false
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false

artifacts:
  #Root location of assessment files [s3://some-bucket/ | classpath: | etc]
  root: ${rdw.resource.root:"classpath:"}
  exam-item:
    directory: item-content/local/items/Item-{0}/
    file-name: item-{0}.xml

application:
  state: CA

permissionservice:
  component: Reporting
  endpoint: ${permission.service}

app:
  iris:
    vendorId: ${iris.vendorId}
    url: ${iris.url}
