sql:
  group:
    findAll: >-
        select sg.id, sg.name, s.name as school_name
          from user_student_group usg
            join student_group sg on sg.id = usg.student_group_id
            join school s on s.id = sg.school_id
            where user_login=:user_login

    findAllForUsername: >-
      select
      	  sg.id,
          sg.name,
          school.name as school_name,
          subject_id
        from user_student_group usg
      	join student_group sg on sg.id = usg.student_group_id
      	join school on school.id = sg.school_id
      	where user_login=:user_login

    membership:
      findAllForUsername: >-
        select sg.id, sg.subject_id, sg.school_id
          from user_student_group usg
            join student_group sg on sg.id = usg.student_group_id
            where user_login=:user_login

  district:
    findAllIds: >-
      select natural_id, id
        from district
        where natural_id in (:naturalIds)

  school:
    findAllIds: >-
      select natural_id, id
        from school
        where natural_id in (:naturalIds)
