sql:
  group:
    findAllForUsername: >-
      select sg.id, sg.name, school.name as school_name, subject_id
        from user_student_group usg
          join student_group sg on sg.id = usg.student_group_id
          join school on school.id = sg.school_id
        where user_login=:user_login

    membership:
      findAllForUsername: >-
        select sg.id, sg.subject_id, sg.school_id
          from user_student_group usg
            join student_group sg on sg.id = usg.student_group_id
          where user_login=:user_login

    exam:
      findLatestForGroupAndSubject:
        select
            distinct iab_exam.session_id,
            iab_exam.completed_at,
            iab_exam.asmt_id,
            asmt.name as asmt_name,
            asmt.grade_id as asmt_grade
          from iab_exam
            join asmt on iab_exam.asmt_id=asmt.id
          where asmt_id=(
            select asmt_id
              from iab_exam
                join student_group_membership on iab_exam.student_id=student_group_membership.student_id
                join asmt on iab_exam.asmt_id=asmt.id
              where student_group_membership.student_group_id=:group_id
              and asmt.subject_id=:subject_id
              order by completed_at desc
              limit 1
          )
          and session_id is not null

  district:
    findAllIds: >-
      select natural_id, id
        from district
        where natural_id in (:naturalIds)

  school:
    findAllIds: >-
      select natural_id, id
        from school
        where natural_id in (:naturalIds)
