sql:
  admin:
    findWarehouseImports: >-
      SELECT i.id, i.digest FROM import i limit 10;

  assessment:
    reporting:
      findAll: >-
        SELECT
          a.id,
          a.label,
          a.name,
          a.grade_code,
          a.type_id,
          a.subject_id,
          a.school_year,
          a.claim1_score_code,
          a.claim2_score_code,
          a.claim3_score_code,
          a.claim4_score_code,
          a.min_score,
          a.max_score,
          a.cut_point_1,
          a.cut_point_2,
          a.cut_point_3
        FROM asmt a
        WHERE (:label_query IS NULL OR a.label LIKE concat('%', :label_query, '%'))
          AND (:name_query IS NULL OR a.name LIKE concat('%', :name_query, '%'))
        LIMIT :limit

  group:
    findAllDistinctSchoolYears: >-
      select distinct sg.school_year
      from student_group sg
        join school sc on sc.id = sg.school_id
      where sg.deleted = 0
        and ${sql.snippet.basicPermission}

    findAllByQuery: >-
      select sg.id,
        sg.name as group_name,
        sc.name as school_name,
        sc.id as school_id,
        sg.school_year,
        (select count(*) from student_group_membership sgm where sgm.student_group_id = sg.id) as student_count,
        s.code as subject_code
      from student_group sg
        join school sc on sc.id = sg.school_id
        left join subject s on s.id = sg.subject_id
      where sg.school_id = :school_id
        and sg.deleted = 0
        and (sg.subject_id is null or sg.subject_id in (:subject_ids))
        and sg.school_year = :school_year
        and ${sql.snippet.basicPermission}

    delete: >-
      update student_group sg
        join school sc on sg.school_id = sc.id
      set sg.deleted = 1,
        sg.update_import_id = :import_id
      where sg.id = :id
        and ${sql.snippet.basicPermission}

  school:
    findAll: >-
      select name, id, natural_id
      from school sc
      where ${sql.snippet.basicPermission}

  schoolYear:
    findAll: >-
      SELECT year FROM school_year ORDER BY year

  status:
    readTest: >-
      SELECT ist.name FROM import_status ist

  student_group_batch:
    create: >-
      INSERT INTO upload_student_group_batch (status, digest, creator, message, filename)
        VALUES (:status, :digest, :creator, :message, :filename)

    findOne: >-
      SELECT * FROM upload_student_group_batch WHERE id=:id

    findOneByDigest: >-
      SELECT * FROM upload_student_group_batch WHERE digest=:digest LIMIT 1

    sqlFindByCreator: >-
      SELECT * FROM upload_student_group_batch WHERE creator=:creator

  import:
    createQuery: >-
      INSERT INTO import (status, content, contentType, digest, batch) VALUES
        (0, 5, 'admin group modification', :digest, :batch)

    triggerQuery: >-
      UPDATE import
      SET status = 1
      WHERE id = :import_id

  instructionalResource:
    findAll: >-
      SELECT DISTINCT
        GROUP_CONCAT(DISTINCT a.label ORDER BY a.id DESC SEPARATOR ', ') as asmt_label,
        a.type_id as asmt_type_id,
        ir.asmt_name,
        ir.performance_level,
        ir.org_level,
        ir.resource,
        ir.org_id,
        coalesce(district_group.name, district.name, school_group.name) as org_name
      FROM instructional_resource ir
        JOIN asmt a
          ON a.name = ir.asmt_name
        LEFT JOIN district_group
          ON ir.org_level = 'DistrictGroup'
          AND district_group.id = ir.org_id
        LEFT JOIN district
          ON ir.org_level = 'District'
          AND district.id = ir.org_id
        LEFT JOIN school_group
          ON ir.org_level = 'SchoolGroup'
          AND school_group.id = ir.org_id
      LEFT JOIN school sch
        ON sch.district_id = ir.org_id
        OR sch.school_group_id = ir.org_id
      WHERE ir.org_level != 'System'
        AND
        (
          1=:statewide
          OR
          (
            (ir.org_level = 'DistrictGroup' AND district_group.id in (:district_group_ids))
            OR
            (
              ir.org_level = 'District'
              AND
              (
                district.id in (:district_ids)
                OR
                (district.id = sch.district_id AND sch.district_group_id in (:district_group_ids))
              )
            )
            OR
            (
              ir.org_level = 'SchoolGroup'
              AND
              (
                school_group.id in (:school_group_ids)
                OR
                (school_group.id = sch.school_group_id AND (sch.district_id in (:district_ids) OR sch.district_group_id in (:district_group_ids)))
              )
            )
          )
        )
      GROUP BY a.type_id, ir.asmt_name, ir.performance_level, ir.org_level, ir.resource, ir.org_id, district_group.name, district.name, school_group.name

    findOne: >-
      SELECT
        GROUP_CONCAT(DISTINCT a.label ORDER BY a.id DESC SEPARATOR ', ') as asmt_label,
        a.type_id as asmt_type_id,
        ir.asmt_name,
        ir.performance_level,
        ir.org_level,
        ir.resource,
        ir.org_id,
        coalesce(district_group.name, district.name, school_group.name) as org_name
      FROM instructional_resource ir
        JOIN asmt a
          ON a.name = ir.asmt_name
        LEFT JOIN district_group
          ON ir.org_level = 'DistrictGroup'
          AND district_group.id = ir.org_id
        LEFT JOIN district
          ON ir.org_level = 'District'
          AND district.id = ir.org_id
        LEFT JOIN school_group
          ON ir.org_level = 'SchoolGroup'
          AND school_group.id = ir.org_id
      LEFT JOIN school sch
        ON sch.district_id = ir.org_id
        OR sch.school_group_id = ir.org_id
      WHERE ir.org_level != 'System'
        AND ir.org_level = :org_level
        AND ir.asmt_name = :asmt_name
        AND ir.performance_level = :performance_level
        AND ir.org_id <=> :org_id
        AND
        (
          1=:statewide
          OR
          (
            (ir.org_level = 'DistrictGroup' AND district_group.id in (:district_group_ids))
            OR
            (
              ir.org_level = 'District'
              AND
              (
                district.id in (:district_ids)
                OR
                (district.id = sch.district_id AND sch.district_group_id in (:district_group_ids))
              )
            )
            OR
            (
              ir.org_level = 'SchoolGroup'
              AND
              (
                school_group.id in (:school_group_ids)
                OR
                (school_group.id = sch.school_group_id AND (sch.district_id in (:district_ids) OR sch.district_group_id in (:district_group_ids)))
              )
            )
          )
        )
      GROUP BY a.type_id, ir.asmt_name, ir.performance_level, ir.org_level, ir.resource, ir.org_id, district_group.name, district.name, school_group.name

    update: >-
      UPDATE instructional_resource ir
      SET
        ir.resource = :resource
      WHERE ir.org_level != 'System'
        AND ir.org_level = :org_level
        AND ir.asmt_name = :asmt_name
        AND ir.performance_level = :performance_level
        AND ir.org_id <=> :org_id

    create: >-
      INSERT INTO instructional_resource (asmt_name, resource, org_level, performance_level, org_id)
        SELECT DISTINCT
          :asmt_name,
          :resource,
          :org_level,
          :performance_level,
          :org_id
        FROM asmt a
          LEFT JOIN instructional_resource ir
            ON ir.asmt_name = a.name
              AND ir.performance_level = :performance_level
              AND ir.org_level = :org_level
              AND ir.org_id <=> :org_id
        WHERE a.name = :asmt_name
          AND ir.asmt_name IS NULL

    delete: >-
      DELETE FROM instructional_resource
      WHERE org_level != 'System'
        AND org_level = :org_level
        AND asmt_name = :asmt_name
        AND performance_level = :performance_level
        AND org_id <=> :org_id